// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://veuogkgxdjwwosynmfzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZldW9na2d4ZGp3d29zeW5tZnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzgzNzYsImV4cCI6MjA2MDA1NDM3Nn0.K01ppdURUHOoridAAAWgm-_DZDVVOPLch053g8iIysM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);